openapi: '3.0.2'
info:
  title: API My - MOROWALI
  version: '1.0'
servers:
  - url: https://localhost:3000/

paths:
  /auth/cek-login:
    get:
      tags: 
        - login
      summary: cek jwt and get data token
      responses:
        '200':
          description: OK
        '404':
          description: OK
  /api/login:
    post:
      tags: 
        - login
      summary: login 
      responses:
        '200':
          description: OK
